# Generated by Django 4.1.7 on 2023-04-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=32)),
                ('number_of_hours', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('second_name', models.CharField(max_length=16)),
                ('third_name', models.CharField(blank=True, max_length=16, null=True)),
                ('course', models.IntegerField()),
                ('group', models.CharField(max_length=16)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=24)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyRare.student')),
            ],
        ),
        migrations.CreateModel(
            name='Rare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=32)),
                ('rare', models.CharField(max_length=32)),
                ('type', models.BooleanField(choices=[('test', 'test'), ('exam', 'exam')])),
                ('discipline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyRare.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='RecordBook',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyRare.student')),
                ('rare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyRare.rare')),
            ],
        ),
    ]
