# Generated by Django 4.1.7 on 2023-03-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=32)),
                ('rare', models.CharField(max_length=32)),
                ('type', models.BooleanField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=16)),
                ('second_name', models.CharField(max_length=16)),
                ('third_name', models.CharField(max_length=16)),
                ('course', models.IntegerField()),
                ('group', models.CharField(max_length=16)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='RecordBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyRare.student')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=32)),
                ('number_of_hours', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('id_rare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MyRare.rare')),
            ],
        ),
    ]
