# Generated by Django 4.1.7 on 2023-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rare',
            name='type',
            field=models.BooleanField(choices=[('test', 'Зачет'), ('exam', 'Экзамен')]),
        ),
    ]
